pytickets/tickets/forms.py
from flask_wtf import FlaskForm
from wtforms.fields.simple import HiddenField, SubmitField, TextAreaField
from .domain import SCHEMA
from wtforms import validators
from wtforms.fields.core import StringField


class CreateTicketForm(FlaskForm):
    summary = StringField(
        'Summary', [validators.Length(min=10, max=SCHEMA['summary'])])
    description = StringField(
        'Description', [validators.Length(max=SCHEMA['description'])])


class CompleteTicketForm(FlaskForm):
    resolution = TextAreaField('Resolution')
    submit = SubmitField('Done!')

pytickets/__init__.py
import os
from string import Template
from flask import Flask, redirect, g
from flask.helpers import url_for
from werkzeug.utils import import_string
from .config import OKTA_SECRETS_FILE
from flask_oidc import OpenIDConnect

oidc = OpenIDConnect()


def create_app(settings_object='pytickets.config.ProdConfig'):
    app = Flask(__name__)
    cfg = import_string(os.getenv('PYTICKETS_SETTINGS', settings_object))()
    app.config.from_object(cfg)

    save_config(configure_okta, f'{OKTA_SECRETS_FILE.replace(".json",".template.json")}',
                f'{OKTA_SECRETS_FILE}')

    oidc.init_app(app)

    @app.before_request
    def before_request():
        g.environment = app.config.get('ENVIRONMENT')  # pylint: disable=assigning-non-slot
        if oidc.user_loggedin:
            g.user = oidc.user_getinfo(  # pylint: disable=assigning-non-slot
                ["sub", "name", "email"])
        else:
            g.user = None  # pylint: disable=assigning-non-slot

    from . import home
    app.register_blueprint(home.bp)
    app.add_url_rule('/', endpoint='home.index')

    from .tickets import views
    app.register_blueprint(views.bp)

    from .adapters.orm import map_entities
    map_entities()

    return app


def configure_okta(
    template_content,
    client_id=os.getenv('OKTA_CLIENT_ID'),
    secret=os.getenv('OKTA_CLIENT_SECRET'),
    url=os.getenv('OKTA_ORG_URL'),
    uris=os.getenv('OKTA_REDIRECT_URIS')
):
    vars = {
        "OKTA_CLIENT_ID": client_id,
        "OKTA_CLIENT_SECRET": secret,
        "OKTA_ORG_URL": url,
        "OKTA_REDIRECT_URIS": uris,
    }
    return Template(template_content).substitute(**vars)


def save_config(configure, template_path, final_path):
    with open(template_path) as f:
        content = f.read()
    final = configure(content)
    with open(final_path, 'w') as f:
        print(final, file=f)

pytickets/home/__init__.py
from flask import Blueprint, redirect, url_for
from flask.templating import render_template
from pytickets import oidc

bp = Blueprint('home', __name__, template_folder='templates')


@bp.route('/')
def index():
    return render_template('index.html')


@bp.route("/login")
@oidc.require_login
def login():
    return redirect(url_for("tickets.dashboard"))


@bp.route('/logout')
def logout():
    oidc.logout()
    return redirect(url_for('home.index'))

pytickets/tickets/views.py
import uuid
from flask.helpers import flash, url_for
from werkzeug.utils import redirect
from pytickets.tickets.domain import CompleteTicket, CreateTicket, now_utc
from .forms import CompleteTicketForm, CreateTicketForm
from pytickets.adapters.orm import new_session_factory
from pytickets.tickets.handlers.queries import get_open
from pytickets.tickets.handlers.sql import complete_ticket_handler, create_ticket_handler
from pytickets.config import get_datebase_uri
from flask import Blueprint
from flask.templating import render_template
from pytickets import oidc
from functools import partial

bp = Blueprint('tickets', __name__, template_folder='templates',
               url_prefix='/tickets')

session_factory = new_session_factory(get_datebase_uri())

create_ticket_handler = partial(create_ticket_handler, session_factory)
complete_ticket_handler = partial(complete_ticket_handler, session_factory)


@bp.route('/')
@oidc.require_login
def dashboard():
    tickets = get_open(session_factory)
    complete_form = CompleteTicketForm()
    return render_template('dashboard.html', tickets=tickets, complete_form=complete_form)


@bp.route('/new', methods=['GET', 'POST'])
@oidc.require_login
def new():
    form = CreateTicketForm()
    if form.validate_on_submit():
        create_ticket = CreateTicket(form.summary.data, form.description.data)
        ticket_created = create_ticket_handler(create_ticket)
        flash('Ticket created!')
        return redirect(url_for('tickets.dashboard'))
    return render_template('new_ticket.html', form=form)


@bp.post('/complete/<ticket_id>')
@oidc.require_login
def complete(ticket_id):
    form = CompleteTicketForm()
    if form.validate_on_submit():
        complete_ticket = CompleteTicket(
            uuid.UUID(ticket_id), form.resolution.data, now_utc())
        print(f'{complete_ticket=}')
        ticket_completed = complete_ticket_handler(complete_ticket)
        flash('Ticket completed!')
        return redirect(url_for('tickets.dashboard'))

pytickets/templates/_formhelpers.html
{% macro render_field(field) %}
  <dt>{{ field.label }}
  <dd>{{ field(**kwargs)|safe }}
  {% if field.errors %}
    <ul class=errors>
    {% for error in field.errors %}
      <li>{{ error }}</li>
    {% endfor %}
    </ul>
  {% endif %}
  </dd>
{% endmacro %}

pytickets/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <title>{% block title %}{% endblock %} - Ticket Pusher</title>
</head>
<body>
  <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
      <h5 class="my-0 mr-md-auto font-weight-normal">Ticket Pusher</h5>
        <nav class="my-2 my-md-0 mr-md-3">
          <a class="p-2 text-dark" href="/" title="Home">Home</a>
          {% if not g.user %}
            <a class="p-2 text-dark" href="{{ url_for('home.login') }}">Log In</a>
          {% else %}
            <a class="p-2 text-dark" href="{{ url_for('tickets.dashboard') }}">Dashboard</a>
            <a class="p-2 text-dark" href="{{ url_for('home.logout') }}">Logout</a>
          {% endif %}
        </nav>
        <p class="my-md-0">Environment: {{ g.environment }}</p>
  </div>
  <div class="container">
    {% block body %}{% endblock %}
  </div>
  <footer class="text-center">
    For all your ticket pushing needs
  </footer>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
</body>
</html>