pytickets/tickets/forms.py
from flask_wtf import FlaskForm
from wtforms.fields.simple import HiddenField, SubmitField, TextAreaField
from .domain import SCHEMA
from wtforms import validators
from wtforms.fields.core import StringField


class CreateTicketForm(FlaskForm):
    summary = StringField(
        'Summary', [validators.Length(min=10, max=SCHEMA['summary'])])
    description = StringField(
        'Description', [validators.Length(max=SCHEMA['description'])])


class CompleteTicketForm(FlaskForm):
    resolution = TextAreaField('Resolution')
    submit = SubmitField('Done!')

pytickets/tickets/views.py
import uuid
from flask.helpers import flash, url_for
from werkzeug.utils import redirect
from pytickets.tickets.domain import CompleteTicket, CreateTicket, now_utc
from .forms import CompleteTicketForm, CreateTicketForm
from pytickets.adapters.orm import new_session_factory
from pytickets.tickets.handlers.queries import get_open
from pytickets.tickets.handlers.sql import complete_ticket_handler, create_ticket_handler
from pytickets.config import get_datebase_uri
from flask import Blueprint
from flask.templating import render_template
from pytickets import oidc
from functools import partial

bp = Blueprint('tickets', __name__, template_folder='templates',
               url_prefix='/tickets')

session_factory = new_session_factory(get_datebase_uri())

create_ticket_handler = partial(create_ticket_handler, session_factory)
complete_ticket_handler = partial(complete_ticket_handler, session_factory)


@bp.route('/')
@oidc.require_login
def dashboard():
    tickets = get_open(session_factory)
    complete_form = CompleteTicketForm()
    return render_template('dashboard.html', tickets=tickets, complete_form=complete_form)


@bp.route('/new', methods=['GET', 'POST'])
@oidc.require_login
def new():
    form = CreateTicketForm()
    if form.validate_on_submit():
        create_ticket = CreateTicket(form.summary.data, form.description.data)
        ticket_created = create_ticket_handler(create_ticket)
        flash('Ticket created!')
        return redirect(url_for('tickets.dashboard'))
    return render_template('new_ticket.html', form=form)


@bp.post('/complete/<ticket_id>')
@oidc.require_login
def complete(ticket_id):
    form = CompleteTicketForm()
    if form.validate_on_submit():
        complete_ticket = CompleteTicket(
            uuid.UUID(ticket_id), form.resolution.data, now_utc())
        print(f'{complete_ticket=}')
        ticket_completed = complete_ticket_handler(complete_ticket)
        flash('Ticket completed!')
        return redirect(url_for('tickets.dashboard'))

pytickets/tickets/templates/complete_ticket.html
<div class="modal fade" id="completeTicket" tabindex="-1" aria-labelledby="completeTicketLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="completeTicketLabel">Complete Ticket</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form method="POST" action="{{ url_for('tickets.complete', ticket_id = ticket.id) }}">
          {{ complete_form.hidden_tag() }}
          <div class="mb-3">
            {{ complete_form.resolution.label(class="form-label") }}
            {{ complete_form.resolution(class="form-control", rows="3") }}
          </div>
          {{ complete_form.submit(class="btn btn-primary") }}
        </form>
      </div>
    </div>
  </div>
</div>

pytickets/tickets/templates/dashboard.html
{% extends 'layout.html' %}

{% block body %}
<h1 id="text-center">{% block title %}Dashboard{% endblock %}</h1>
<a class="btn btn-primary mb-3" role="button" href="{{ url_for('tickets.new') }}">Create Ticket</a>
<!-- <div id="row">
    <div class="col-sm-8 offset-sm-2">
        <p>Welcome to the dashboard, {{ g.user.name }}!</p>
        <p>Your user id is {{ g.user.sub }}!</p>
    </div>
</div> -->
{% for ticket in tickets %}
  <div class="card">
    <div class="card-body">
      <p class="card-text">{{ ticket.summary }}</p>
    </div>
    <div class="card-body">
      <div class="accordion">
        <div class="accordion-item">
          <h2 class="accordion-header" id="pushTo">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-{{ ticket.id }}" aria-expanded="false" aria-controls="collapse-{{ ticket.id }}">
              Push To...
            </button>
          </h2>
          <div id="collapse-{{ ticket.id }}" class="accordion-collapse collapse" aria-labelledby="heading-{{ ticket.id }}">
            <div class="accordion-body">
              <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#completeTicket">
                Completed
              </button>
              {% include 'complete_ticket.html' %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endfor %}
{% endblock %}

pytickets/tickets/templates/new_ticket.html
{% extends 'layout.html' %}
{% from '_formhelpers.html' import render_field %}

{% block body %}
<h1 id="text-center">{% block title %}New Ticket{% endblock %}</h1>
<form method="POST">
  {{ form.hidden_tag() }}
  <dl>
    {{ render_field(form.summary) }}
    {{ render_field(form.description) }}
  </dl>
  <input type=submit value=Create>
</form>
{% endblock %}